#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KitchenTimer.Resource", IsApplication=true)]

namespace KitchenTimer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int Add10MinButton = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int Add10SecButton = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Add1MinButton = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int Add1SecButton = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int ClearButton = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int RemainingTimeTextView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int StartButton = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int linearLayout1 = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int linearLayout2 = 2130968583;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
